### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by jmgirard** [jmgirard/agreement#1]
- [x] Add functions for chance-adjusted agreement coefficients
- [x] Add unit testing for chance-adjusted agreement coefficients
- [x] Add functions for ICC Model 1
- [x] Add functions for ICC Models 2 and 2A
- [ ] Add functions for ICC Models 3 and 3A
- [ ] Add unit testing for ICC functions
- [ ] Check the calculation of intra-rater reliability with consistency ICCs
- [ ] Re-implement bootstrapping in Rcpp for optimized speed
- [ ] Add clustered bootstrapping for hierarchical data
- [ ] Add ability to include multiple "score" variables in ICC functions

**Comment by fvv9** [comment]
Hi!  When using the dim_icc function I am getting this error:

Error in eval(parse(text = paste0("calc_icc_", model, ifelse(type == "agreement",  : 
  object 'calc_icc_3A_A' not found

I've got version 0.0.0.9003 on R 4.4.0.  

Thanks!
